### ISSUE TITLE
Error al correr createCert - Validacion de alias

### ISSUE THREAD

**Issue by federiva** [AfipSDK/afip.py#1]
Muchas gracias por este paquete! :smile: 
Si te parece forkeo y armo PR

**TL;DR** 
Agregar una validación en la clase para el input del alias cuando se corre el metodo `createCert` en `Afip`

En la documentacion online dice:
```
# Alias para el certificado (Nombre para reconocerlo en AFIP)
# un alias puede tener muchos certificados, si estas renovando
# un certificado podes utilizar el mismo alias
cert_alias = "afipsdk"
```
Estuve peleando bastante y terminé yendo a la web para generar el certificado y ahí me di cuenta de que en la consola de python estaba agregando un caracter especial para identificar el certificado. Mensaje que claramente no venia en la respuesta de la API `{"status":"error","data":{"message":"Unable to get cert, try again"}}`

![image](https://github.com/AfipSDK/afip.py/assets/25372718/f92f4666-263c-4d97-9e96-647c22fbcce5)

El error que devuelve la API es
![image](https://github.com/AfipSDK/afip.py/assets/25372718/e92da729-90de-4d20-b553-c96957330e59)

**Comment by ivanalemunioz** [comment]
Gracias @federiva  por la colaboración, ya quedo agregado el checkeo en el lado del servidor para dar aviso
