### ISSUE TITLE
En producción: Debe setear el sdk en modo testing

### ISSUE THREAD

**Issue by awisky** [AfipSDK/afip.py#2]
El problema que encontré  con la suscripción  paga.
Intentando utilizar la librería en producción con los certificados con sus alias respectivos y autorizaciones validadas en el website de Afip:
`Exception: {"statusCode":400,"message":"Debe setear el sdk en modo testing. Agregue \"production: false\" al instanciar la libreria . ns1:cms.cert.untrusted"}`

No puedo hacer las consultas en Afip ambiente productivo. solo testing.

**Comment by AfipSDK** [comment]
Dicho error aparece cuanto intentas usar un certificado de testing en modo
producción. El certificado que obtuviste es de producción o testing?
https://docs.afipsdk.com/paso-a-paso/tutoriales-pagina-de-afip/obtener-certificado-de-produccion
